# Обработка исключений

Конструкция try..catch

Обработка исключительных ситуаций (exception handling) — механизм, предназначенный для описания реакции программы на ошибки времени выполнения и другие возможные проблемы (исключения), которые могут возникнуть при выполнении программы и приводят к невозможности (бессмысленности) дальнейшей отработки программой её базового алгоритма.  

В С# исключения представлены в виде классов. Все классы исключений должны быть производными от встроенного в С# класса `Exception` являющегося частью пространства имен System. Следовательно, все исключения в C# являются подклассами класса `Exception`

## Блок try.. catch

```c#
private voidSomeMethod()
{
    try
    {
        // Код требующий корректного восстановления
        // или очистки ресурсов
    }
    catch (InvalidOperationException)
    {
        // Код востановления операции        
    }
    catch
    {
        // Код восстановления после остальных исключений
    }
    // !!!! Этот блок отработает даже если небыло исключений
    finally
    {
        // Обычно здесь находится код, выполняющий очистку ресурсов
        // после операции начатых в блоек try        
    }
}
```

## Варианты использования блока catch

### Отлавливаем исключение типа Exception и получаем доступ к его контексту

```c#
catch (Exception e)
{
       
}
```

### Отлавливаем исключение типа Exception, контекст не доступен

Если мы не получаем переменную ошибки можно посмотреть ее в консоли отладки создав там переменную `$exception`

```c#
catch (Exception)
{

}
```

### В таком виде блок catch отловит любое исключение

```c#
catch
{
       
}
```

## Поднятия исключений по стеку

В блоке `catch` можно сгенерировать новое исключение или вызвать полученное исключение

### Генерируем новое исключение и выбрасываем его выше по стеку вызова

```c#
try
{
    // ...
}
catch
{
    throw new Exception();
}
```

### Выбрасываем полученное исключение выше по стеку вызова

```c#
try
{
    // ...
}
catch
{
    throw;
}
```

## Для создания пользовательского исключения, нужно наследоваться от класса Exception

```c#
class UserException : Exception
{
    public void Method()
    {
        Console.WriteLine("Мое исключение");
    }
}
```
